package profbio.ufpb.mestrado.desvendandoascelulastronco.model;

import java.util.Arrays;
import java.util.List;

public class QuestionsData {

    private static Question[] questions = new Question[]{
        new Question(1, "Imagine você assumindo um grande centro de pesquisas especializado em estudo das células-tronco (CT) e diante da grande relevância desempenhada por tal grupo celular, sabendo que possuem a função de produzir todos os tipos celulares existentes no corpo humano, quais são as três categorias que se dividem as células-tronco?", "Células-tronco embrionárias (CTE), Células-tronco adultas (CTA) e Células-tronco induzidas (iPS).", "Células-tronco estomacais (CTE), Células-tronco cerebrais (CTC) e Células-tronco umbilicais (CTU).", "Células-tronco adultas (CTA), Células-tronco mesodérmicas (CTM) e Células-tronco intersticiais (CTI).", "embrião, medula-óssea, laboratório.", 1),
        new Question(2, "Diante dos conhecimentos adquiridos e baseado na capacidade das células-tronco de realizar autorrenovação e diferenciação, como você define células-tronco totipotentes?", "são aquelas que possuem a capacidade de gerar todos os tipos celulares, com exceção dos tecidos extraembrionários.", "são aquelas que possuem capacidade de dar origem a todos os tipos celulares, inclusive tecidos embrionários e extraembrionários.", "são aquelas que possuem a capacidade de transformar-se em qualquer célula de um indivíduo adulto.", "ampla diferenciação.", 2),
        new Question(3, "As Células-Tronco Pluripotentes Induzidas (iPS) são produzidas em laboratório, onde ocorre a __________________  de células adultas de um determinado organismo_____________ induzindo-as a expressar fatores de transcrição, levando a este grupo celular a desdiferenciação celular e recuperando as características presente nas ____________, a _________________. Os termos que preenchem respectivamente os espaços acima são:", "Diferenciação, embrionário, CTH e unipotência.", "Reprogramação, adulto, CTE e pluripotência.", "Degeneração, adulto, CTM e pluripotência.", "ato de reprogramar, maduro, embrião, produção de vários tipos celulares.", 2),
        new Question(4, "Os estudos envolvendo as CTA nos últimos anos, sugeriram que as mesmas podem ter a capacidade de se diferenciar em tipos de células de diferentes camadas germinativas. Por exemplo, células-tronco neurais do cérebro; que são derivados do ectoderma, podem se diferenciar em ectoderme, mesoderme e endoderme. Este fenômeno é referido como transdiferenciação de CT. Pode ser induzida pela modificação do meio de crescimento quando as CT são cultivadas in vitro ou transplantadas para um órgão do corpo diferente daquele do qual foram originalmente isoladas. A grande característica das células-tronco evidenciada no texto acima é caracterizada pela sua (s):", "Plasticidade.", "Linhagem evolutiva.", "Propriedades.", "versatilidade.", 1),
        new Question(5, "Leia a notícia abaixo:\n" +
                "“Cientistas afirmam terem conseguido transformar, em laboratório, células da própria pele de pacientes em tecido de coração. Em última análise, eles esperam que as células-tronco (CT) possam ser utilizadas para tratar pacientes com insuficiência cardíaca. (...) Especialistas têm usado cada vez mais CT para tratar uma variedade de problemas cardíacos e outras condições como o diabetes, doença de Parkinson ou Mal de Alzheimer.” (http://g1.globo.com/ciencia-esaude/noticia/2012/05/cientistas-conseguem-transformar-celulas-da-pele-em-tecido-cardiaco.html).\n" +
                "Se imaginem como cientistas especializados no estudo com CT. Como você distingue células-tronco adultas (CTA) como as do texto, de células-tronco embrionárias (CTE)?\n", "São CT que geram células de apenas um dos três folhetos embrionários e originam um número limitado de certos tipos celulares.","São CT que originam somente o tecido hemocitotopoiético e células do tecido conjuntivo.", "São CT que originam todos os tipos de células e tecidos do corpo.", "totipotência.", 3),
        new Question(6, "Todo paciente que se submete a um transplante deve ter ciência que durante o resto de sua vida, ou em parte dela, deverá se submeter a administração de medicamentos para evitar que seu corpo inicie um processo inflamatório contra o órgão recém chegado (rejeição). Pacientes que se submetem a transplantes em todo mundo, enfrentam processos de rejeição, e para isso vem sendo utilizado em grandes centros médicos uma técnica inovadora que consiste na retirada e inoculação de células-tronco do próprio paciente (conhecida como autotransplante) na intenção de minimizar tais complicações. Tal técnica vem obtendo resultados satisfatórios por parte transplantados e sendo bem aceita na terapêutica de tais pacientes. O autotransplante apresenta capacidade reduzida de desenvolver problemas de rejeição em comparação com os transplantes tradicionais realizados entre diferentes indivíduos. Tudo em decorrência de as:", "células-tronco mantêm-se indiferenciadas após sua introdução no organismo do receptor.", "células provenientes de transplantes entre diferentes indivíduos envelhecem e morrem rapidamente.", "células-tronco, por serem doadas pelo próprio indivíduo receptor, apresentam material genético semelhante.", "material do próprio indivíduo.", 3),
        new Question(7, "O estudo com células-tronco a cada dia ganha mais força em pesquisas no mundo científico. Desde a década de 1990, quando células do cordão umbilical de recém-nascidos humanos começaram a ser guardadas em um processo denominado de criopreservação, pelo alto potencial terapêutico em consequência de suas características peculiares. Como você caracteriza tal potencialidade e capacidade do uso terapêutico de tais células?", "seu potencial de adesão a diferentes tecidos.", "seu potencial de diferenciação em células especializadas.", "seu potencial de reconhecimento de células semelhantes.", "ampla versatilidade.", 2),
        new Question(8, "As CT’s possuem alto poder de diferenciação. Alguns tipos, no entanto, apresentam potencial reduzido quando comparados com outros tipos dessas células. A CT capaz de se diferenciar em tipos específicos de células (como célula-tronco mesenquimal, célula-tronco derivada de tecido adiposo, célula-tronco endotelial, etc.) é:", "totipotente.", "pluripotente.", "multipotente.", "diferenciação em muitos tipos celulares.", 3),
        new Question(9, "As células-tronco adultas e as embrionárias possuem a capacidade de proliferação e especialização quando transplantadas para animais cujo sistema imunológico tenha sido__________ e são utilizadas em terapêuticas principalmente pelo pequeno potencial de ________________", "Estimulada, supressão.", "Suprimido, rejeição.", "Mantida, acepção.", "baixa da ação imunitária, reação.", 2),
        new Question(10, "A diferenciação celular constitui um processo biológico complexo e vital, uma vez que regula a expressão de um grande número de genes ligados a funções tecido-específicas e controla a proliferação celular. Trata-se de um mecanismo de:", "especialização das células, gerando uma grande diversidade de formas celulares capazes de realizar distintas funções.", "especialização que acarreta só alterações da função das células, determinando a única função para ela determinada.", "especialização celular em que apenas um grupo único de células se originada a partir de processos mitóticos ao final de todo o processo.", "especificação em diversos tipos celulares.", 1),
        new Question(11, "As CT’s possuem alto poder de diferenciação. Alguns tipos, no entanto, apresentam potencial reduzido quando comparados com outros tipos dessas células. A CT capaz de se diferenciar em tipos específicos de células (como célula-tronco mesenquimal, célula-tronco derivada de tecido adiposo, célula-tronco endotelial, etc.) é:", "totipotente.", "pluripotente.", "multipotente.", "diferenciação em muitos tipos celulares.", 3),
        new Question(12, "Verifica-se, algumas vezes, certa confusão na compreensão do conceito de célula-tronco embrionária (CTE). Para compreensão deste grupo celular, é extremamente necessário demonstrarmos o estágio de desenvolvimento em que ela ocorre. Qual a definição correta para esse grupo de células?", "Denominadas assim, por serem células derivadas da massa celular interna de um blastocisto, um estágio inicial de pré-implantação no útero. Os embriões humanos atingem a fase de blastocisto por volta de 4-5 dias após a fertilização, sendo constituídas em média de 50-150 células.", "Denominadas assim por serem células reprogramadas que atuam no organismo com a capacidade de transformarem-se em qualquer outro tipo celular. São obtidas a partir de produção em laboratório, sendo utilizadas pela primeira vez em 2006, pelo pesquisador japonês chamado Shinya Yamanaka em camundongos.", "São células indiferenciadas, encontradas em todo nosso corpo após o desenvolvimento, multiplicam-se através da divisão celular com o intuito de repor as células que estão morrendo, assim como, regenerar os tecidos danificados. Também denominadas células-tronco somáticas, elas podem ser encontradas tanto em animais jovens como adultos e humanos.", "células derivadas do embrião.", 1),
        new Question(13, "Existe um tipo de células-tronco originadas pela primeira vez em 2006 por dois cientistas japoneses, Takahashi e Yamanaka. A partir de fibroblastos embrionários e adultos de camundongos, foi possível elaborar um tipo celular com características de CTE, levando a conseguirem expressar uma característica bastante particular de célula embrionária, a pluripotência (TAKAHASHI e YAMANAKA, 2006). Diante dos impasses éticos na utilização de células-tronco, cientistas e médicos estão entusiasmados a respeito deste novo tipo de células tronco chamadas células “iPS”. Razão pela qual as iPS possuírem praticamente as mesmas propriedades das células tronco embrionárias, mas não são obtidas de um embrião. Diante do exposto acima e relembrando os conhecimentos adquiridos nas aulas de biologia, a produção deste grupo de células-tronco se dá através de (a):", "Reprogramação celular realizada em laboratório, onde células de organismos adultos são retiradas e induzidas a expressar fatores de transcrição, levando a este grupo celular a desdiferenciação celular e recuperando as características presente nas CTE, a pluripotência. Por conta de tal capacidade é esperado que as iPS revolucionem a medicina regenerativa num futuro próximo.", "Reprogramação celular feita no interior do organismo humano em que consiste na renovação total das células-tronco de um determinado organismo. O ponto negativo de tal procedimento é a baixa na imunidade do paciente.", "Diferenciação celular presente apenas nas células nervosas e frequentes na produção de células sanguíneas. Este método é bem visto pela comunidade científica como uma possibilidade futura na cura de doenças genéticas.", "células reorganizadas em laboratório.", 1),
        new Question(14, "A clonagem tem sido utilizada com frequência nos dias atuais, para propagação das espécies de plantas ou bactérias. Na espécie humana, existem os clones naturais que são os gêmeos idênticos originando-se da divisão de um mesmo óvulo fertilizado. No ano de 2006, foi apresentada ao mundo científico, a ovelha Dolly, primeira ovelha clonada no mundo, abrindo-se assim, caminho para a possibilidade de clonagem humana ao demonstrar, pela primeira vez, que era possível clonar um mamífero - isto é, produzir uma cópia geneticamente idêntica, a partir de um tipo de célula-tronco. Diante do exposto anteriormente que tipo de célula-tronco foi utilizada para a produção da ovelha Dolly?", "Célula-tronco induzida, onde uma célula somática foi usada e reprogramada, retirando-se o seu material genético e colocando-o em um óvulo anucleado que posteriormente foi implantado no útero comportando-se como um óvulo recém fecundado pelo espermatozóide.", "Célula-tronco embrionária, onde foi implantado no útero da ovelha mãe uma célula retirada do cordão umbilical de uma ovelha recém-nascida. Esta se desenvolveu, multiplicou-se e gerou um indivíduo idêntico a ovelha recém-nascida doadora da célula-tronco.", "Célula-tronco adulta, onde foi implantado uma célula retirada da medula-óssea de uma ovelha. Esta se desenvolveu, multiplicou-se e gerou um indivíduo idêntico a progenitora.", "iPS.", 1),
        new Question(15, "Em 1999, estudo publicado pela revista Science no artigo Capturing the Promise of Youth, apontaram as células-tronco como “Scientific Breakthrough oftheYear” (avanço científico do ano). Naquele ano, foi demonstrado que células-tronco de tecidos adultos mantinham a capacidade de se diferenciar em outros tipos de tecidos. Este grupo celular, caracterizados por serem células indiferenciadas, possuem uma série de características que as tornam candidatas à utilização terapêutica. As principais características das células-tronco são, EXCETO:", "A capacidade de autorrenovação e de se diferenciarem em diversos tipos celulares.", "A incapacidade de formar partes do corpo do feto em desenvolvimento.", "A possibilidade de utilização deste grupo de células para cura de doenças até então incuráveis.", "diferenciação em qualquer tipo celular fetal.", 2),
        new Question(16, "As CT’s podem ser agrupadas em três categorias: Células-tronco embrionárias (CTE), Células-tronco adultas (CTA) e Células-tronco induzidas (iPS). Cada grupo citado acima possui características típicas que os diferenciam entre si.\n" +
                "\n" +
                "I. Grupo de células que foram produzidas em laboratório a partir da reprogramação celular; \n" +
                "II. Também denominadas células-tronco somáticas, elas podem ser encontradas tanto em animais jovens como adultos e humanos. Células isoladas de diferentes tecidos ou estruturas do corpo, como medula óssea, polpa de dente e tecidos adiposo e epitelial;\n" +
                "III. Células pluripotentes podem obtidas da massa celular interna do blastocisto.\n" +
                "\n" +
                "A sequência correta a que se retrata cada alternativa acima, respectivamente, é:", "CTE, CTA e iPS.", "iPS, CTA e CTE.", "CTA, CTE e iPS.", "reorganizadas em laboratório, produzidas na medula-óssea, presentes nos embriões.", 2),
        new Question(17, "Embora existam questões éticas e bioéticas interessantes em torno da coleta e uso de células-tronco adultas de fetos abortados e sangue do cordão umbilical, a controvérsia mais intensa até hoje se concentra no uso de células-tronco embrionárias humanas, e envolvem sua derivação e uso para pesquisa. Ou seja, a remoção da massa de células primordiais dos blastocistos, os impede de continuar seu desenvolvimento. Diante do exposto acima, a alternativa abaixo que mais representa os anseios e batalhas no uso de tais células é (são):", "A obtenção desse material biológico e a aplicabilidade clínica dessas novas modalidades terapêuticas ainda está muito distante para a maioria das doenças.", "Os limites terapêuticos da utilização das células-tronco e, principalmente, as afecções neurológicas crônicas graves e seus familiares que, nos dias de hoje, ainda não fomos contemplados com este método terapêutico.", "O embate entre as ideologias (filosófica, religiosa, científica,  bioética) que não chegaram a um consenso sobre o momento exato em que a vida começa, isto é, se embriões em fase tão insipiente merecem proteção; e direitos legais e morais iguais aos das pessoas nascidas, por carregarem material genético humano.", "religião, utilização, início da vida.", 3),
        new Question(18, "O primeiro relato de estudos envolvendo a temática células-tronco embrionárias humanas foi publicado na revista científica Science, no ano de 1998, pela equipe formada por James A. Thomson, da Universidade de Wisconsin/EUA. Nesta pesquisa foram isoladas e cultivadas, células-tronco, a partir de embriões doados por casais que não tinham mais a intenção de usá-los para seu próprio tratamento de infertilidade. A partir de então, a pesquisa nesse campo mergulhou em controvérsias éticas consequentes de um desconforto público quanto aos possíveis impactos negativos a esta e às futuras gerações, já que a obtenção do material genético implica, necessariamente, na interrupção do desenvolvimento de um embrião. Desde então a pesquisa com células-tronco embrionárias despertou inquietações profundas (possibilidade de clonagem humana; mistura de espécies entre homens e animais (quimeras); mercantilização do material biológico humano e, mesmo, à imortalidade). Embora preocupações públicas sobre a Ciência e suas implicações não sejam novas em si, tais estudos seguem regras ou leis na sua utilização em nosso país, seguindo a seguinte lei bioética:", "LEI Nº 11.105, DE 24 DE MARÇO DE 2005 que rege e regulamenta normas de segurança e mecanismos de fiscalização de atividades que envolvam organismos geneticamente modificados – OGM e seus derivados, cria o Conselho Nacional de Biossegurança – CNBS.", "DECRETO LEI 2838/40 DO CÓDIGO PENAL, DE 7 DE DEZEMBRO DE 1940, que regulamenta a utilização de tais células para fins terapêuticos e reprodução assistida, seguindo parâmetros de segurança, fiscalização e utilização de tais materiais.", "LEI Nº 9.434, DE 4 DE FEVEREIRO DE 1997, que regulamenta a manipulação de embriões em laboratório para fins terapêuticos e reprodução assistida, bem como sua utilização na produção de órgãos artificiais para possíveis doadores.", "normas de segurança para organismos vivos.", 1),
        new Question(19, "As Célula-Tronco Hematopoiéticas (CTH) são tipos de CTA responsáveis pela manutenção da produção dos diversos tipos de células sanguíneas, como as hemácias, os granulócitos, os linfócitos, os monócitos e os megacariócitos (de onde se originam as plaquetas), tendo a capacidade de produzir cerca de 3 milhões de células do sangue por segundo. Este grupo de células, em estudos recentes, apontaram para desfechos eficientes e que poderão ser utilizados no tratamento de mais de 80 tipos de doenças do sangue. De acordo com seus conhecimentos prévios e os adquiridos durante a exploração do App, conseguimos encontrar tal grupo de células-tronco no (a):", "Medula óssea ou cordão umbilical.", "Córtex cerebral ou na medula oblonga.", "Dentição decídua ou na medula renal.", "doenças relacionadas com o distrito sanguíneo.", 1),
        new Question(20, "As Célula-Tronco Mesenquimais (CTM) são células encontradas em pequenas quantidades nos tecidos e são responsáveis originalmente pelo suporte a produção de células do sangue (hematopoese). As CTM apresentam grande potencial de proliferação e atuam na regeneração de tecidos danificados, ou seja, são capazes de se transformar primordialmente em:", "osso, gordura, tendão, cartilagem, músculo, sangue, geléia de Wharton do cordão umbilical e dentes", "células do trato gastrointestinal, do nervo ciático, da via de saída cardíaca e dos gânglios espinhais e simpáticos, podem gerar neurônios, células de Schwann, miofibroblastos, condrócitos e melanócitos.", "grupo raro e controverso (discutem-se muito sobre suas capacidades), com a capacidade de se diferenciar em células endoteliais que revestem os vasos sanguíneos.", "subpopulação das células-tronco da medula óssea.", 1),
        new Question(21, "As células-tronco adultas (CTA) são células indiferenciadas, encontradas em todo nosso corpo após o desenvolvimento, multiplicam-se através de sucessivas mitoses com o intuito de repor as células que estão morrendo, assim como, regenerar os tecidos danificados. Também denominadas células-tronco somáticas, elas podem ser encontradas tanto em animais jovens como adultos e humanos, ao contrário das CTE. Uma célula-tronco adulta possui duas propriedades:", "Auto-renovação- habilidade de passar por numerosos ciclos de divisão celular enquanto ainda mantém seu estado indiferenciado e Multipotência ou potencial multidiferenciativo - capacidade de gerar progênie de vários tipos distintos de células (por exemplo, células gliais e neurônios).", "Auto-renovação - habilidade de passar por numerosos ciclos de divisão celular enquanto ainda mantém seu estado indiferenciado e Pluripotência ou Totipotência – capacidade de diferenciação em qualquer célula fetal durante todo o processo de formação.", "Clonogênese – capacidade de originar células idênticas as existentes e Unipotência – habilidade das células que são restritas a produzir um tipo de célula única.", "Ação ou efeito de renovar por divisões mitóticas, capacidade de diferenciação em vários tipos celulares.", 1),
        new Question(22, "As CTA são tipos celulares que podemos encontrar em diversas partes do corpo humano (sangue, placenta, medula-óssea, etc.) e que possuem a função de renovação e reparação tecidual. Elas não são derivadas de tecidos embrionários e possuem a capacidade de se transformarem em menor escala. Em outras palavras, as CTA apresentam maior dificuldade para se dividirem que as embrionárias e, por isso, as pesquisas atuais utilizam em grande parte as CTE, com o intuito de produzirem outras células. Existe um grupo de CTA que é um dos três tipos de CT multipotentes encontradas na medula óssea. Essas células são um grupo raro e controverso (discutem-se muito sobre suas capacidades), com a capacidade de se diferenciar em células que revestem os vasos sanguíneos. Este grupo de CTA é denominado de:", "CT endoteliais.", "CT neurais.", "CT intersticiais.", "formam e revestem os vasos sanguíneos.", 1),
        new Question(23, "Ainda é difícil de entender nos dias atuais como todos nós, formados aproximadamente por mais de três trilhões de células, já fomos uma única no momento da fecundação, o zigoto. E também imaginarmos que antes mesmo desse zigoto, em um estágio superior a 100 células (blástula) e antes da chegada ao útero materno para se implantarimplantação, aconteceram as primeiras divisões e diferenciações celulares. É um processo único e perfeito responsável pela estruturação do nosso corpo.Ainda é difícil de entender nos dias atuais como todos nós, formados aproximadamente por mais de três trilhões de células, já fomos uma única no momento da fecundação, o zigoto. E também imaginarmos que antes mesmo desse zigoto, chegar ao útero materno para se implantar, aconteceram as primeiras divisões e diferenciações celulares. É um processo único e perfeito responsável pela estruturação do nosso corpo. Mas o que seria na verdade o processo de diferenciação celular?", "Processo em que células se especializam para originarem as diversas células existentes nos organismos vivos, proporcionando a capacidade de desempenharem funções distintas.", "Processo de aumento gradual da capacidade de originar células progenitoras durante a fecundação.", "Processo de descarte de células envelhecidas e que precisam ser retiradas do interior do organismo humano.", "formação de diferentes células.", 1),
        new Question(24, "A terapêutica da utilização de CT retiradas do próprio indivíduo (Autotransplante) é liberada em relação a implicações éticas que envolvem o uso de embriões, pois utiliza CTA retiradas do próprio paciente. Apesar disso, esse tipo de terapia é inadequado no tratamento de doenças genéticas que o paciente possua pelo fato de:", "as CT serão rejeitadas pelo sistema imunológico do paciente devido ao encontro dos genes alterados presentes no implante.", "as CT do implante apresentam genes inativos, prejudicando a recomposição do tecido lesado.", "as CT do implante possuem a constituição do genoma semelhante à do tecido a ser recuperado o que não solucionará a doença genética apresentada.", "genoma semelhante.", 3),
        new Question(25, "Com o avanço da biotecnologia e estudos com células-tronco, vislumbra-se no futuro próximo a produção em laboratório de órgãos, tecidos e células que possam ser direcionadas para fins terapêuticos como transplantes, implantes e reposição de áreas afetadas. Diante do que foi apresentado no App Desvendando as Células-Tronco e com seus conhecimentos sobre o assunto, qual grupo de células-tronco poderia ser utilizado sem complicações éticas?", "Células-Tronco de Pluripotência Induzida – IPS", "Células-Tronco Embrionárias – CTE", "Células-Tronco Adultas – CTA", "?", 1),
    };

    public static List<Question> getQuestions() {
        return Arrays.asList(questions);
    }

}
